### ISSUE TITLE
ask a question

### ISSUE THREAD

**Issue by folkaholic** [nickgkan/semantic-visual-relationships#1]
please tell me where can I download 'cell_obj2vec.mat' ?
I want to run your code to learn something about this paper.

**Comment by nickgkan** [comment]
Dear @folkaholic this is an old and incomplete repository and I was planning to delete it before I saw your question.

You can refer now to https://bitbucket.org/deeplabai/vrd/src/master/ that contains the code for our latest paper "Deeply Supervised Multimodal Attentional Translation Embeddings for Visual Relationship Detection". The tests are on VRD as well and the paper is scheduled to be announced on Arxiv tonight.

If you have any questions on the dataset, the code or the paper, please open an issue to that repo or mail me.

**Comment by folkaholic** [comment]
> Dear @folkaholic this is an old and incomplete repository and I was planning to delete it before I saw your question.
> 
> You can refer now to https://bitbucket.org/deeplabai/vrd/src/master/ that contains the code for our latest paper "Deeply Supervised Multimodal Attentional Translation Embeddings for Visual Relationship Detection". The tests are on VRD as well and the paper is scheduled to be announced on Arxiv tonight.
> 
> If you have any questions on the dataset, the code or the paper, please open an issue to that repo or mail me.

thank you！I will read your paper as soon as possible for further learning :)
